name: Ticket Monitor

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}      # manual trigger option

permissions:
  contents: write   # needed to commit updated CSV back to repo

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python monitor.py

      - name: Save history (commit CSV if changed)
        run: |
          if [ -f data/price_history.csv ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/price_history.csv
            git commit -m "chore: update ticket history [skip ci]" || echo "No changes"
            git push
          fi
